# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o tidy

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o tidy.exe

    - name: Upload Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: tidy
        path: tidy

    - name: Upload Windows Binary
      uses: actions/upload-artifact@v3
      with:
        name: tidy.exe
        path: tidy.exe